version: '3'

vars:
  MULTICAST_ADDR: 225.0.0.1

tasks:
  build-globe:
    desc: Build the display server.
    cmds:
      - go build -o bin/tile main.go

  run-globe:
    desc: Start a display server.
    cmds:
      - go run cmd/globe/globe.go

  globe-dev-play:
    desc: Request a local globe to play a file with a crop.
    cmds:
      - curl -d "file=terminator.mp4&top=400" -X POST http://localhost:8081/play

  globe-dev-stop:
    desc: Request a local globe to play a file with a crop.
    cmds:
      - curl -d "file=terminator.mp4&top=400" -X POST http://localhost:8081/stop
      -
  sync-to-pi:
    desc: Sync source code (not binaries) to pi. Pass pi IP as arg.
    cmds:
      - rsync -avz --exclude bin . pi@{{.CLI_ARGS}}:~/wall-of-globes

  multicast-stream:
    desc: Start streaming a file to a multi-cast address (default 225.0.0.1). Pass the file path as arg.
    cmds:
      - echo "vlc -vvv {{.CLI_ARGS}} --sout udp:{{.MULTICAST_ADDR}}"

  play-stream:
    desc: Play a stream from a multi-cast address with a crop (with pi video args).
    cmds:
      - echo "vlc -vvv udp://@{{.MULTICAST_ADDR}} --video-filter=croppadd{croptop=100} --codec avcodec,none"
