version: '3'

vars:
  MULTICAST_ADDR: 225.0.0.1

tasks:
  build-tile:
    cmds:
      - go build -o bin/tile main.go

  sync-to-pi:
    cmds:
      - rsync -avz --exclude bin . pi@{{.CLI_ARGS}}:~/wall-of-globes

  multicast-stream:
    cmds:
      - echo "vlc -vvv {{.CLI_ARGS}} --sout udp:{{.MULTICAST_ADDR}}"

  play-stream:
    cmds:
      - echo "vlc -vvv udp://@{{.MULTICAST_ADDR}}"